# overall operations
general:
  load_from_scratch: False
  save_raw_dataframe: False
  save_transformed_dataframe: True
  remove_bad_values: True

# categorize columns
columns:
  categorical:
    - "neighbourhood_group"
    - "room_type"
  continuous:
    - "minimum_nights"
    - "number_of_reviews"
    - "reviews_per_month"
    - "calculated_host_listings_count"
    - "latitude"
    - "longitude"
  date:
    - "last_review"
  text:
    - "name"
    - "host_name"
  excluded: # columns to not include in training as input features
    - "price"
    - "id"

# default values to replace missing values
category_defaults:
  categorical: missing
  continuous: 0.0
  text: missing
  date: 2019-01-01
  excluded: missing

# values to replace invalid values
category_invalid_replacements:
  categorical: bad_categorical
  continuous: bad_continuous
  text: bad_text
  date: bad_date
  excluded: bad_excluded
latitude_replacement: bad_latitude
longitude_replacement: bad_longitude

# columns where only non-negative values are valid
non_negative_continuous:
  - "minimum_nights"
  - "number_of_reviews"
  - "reviews_per_month"
  - "calculated_host_listings_count"

# valid values for columns with defined set of valid values
valid_values:
  neighbourhood_group:
    - "Bronx"
    - "Brooklyn"
    - "Queens"
    - "Manhattan"
    - "Staten Island"
  room_type:
    - "Private room"
    - "Shared room"
    - "Entire home/apt"

# latitude and longitude bounding boxes for New York City
bounding_box:
  max_long: -73.70018092
  max_lat: 40.91617849
  min_long: -74.25909008
  min_lat: 40.47739894
# latitude and longitude bounding boxes for Newark New Jersey
newark_bounding_box:
  max_long: -74.11278706
  max_lat: 40.67325015
  min_long: -74.25132408
  min_lat: 40.78813864

# geospatial columns
geo_columns:
  - "latitude"
  - "longitude"

# file names:
file_names:
  input_csv: AB_NYC_2019.csv
  pickled_input_dataframe: AB_NYC_2019_input_nov8.pkl
  pickled_output_dataframe: AB_NYC_2019_output_nov8.pkl
